spring.application.name=DemoApplication
spring.data.mongodb.uri=mongodb+srv://admin:somya123@cluster0.xwsqs.mongodb.net/carDatabase?retryWrites=true&w=majority
#spring.data.mongodb.database=employees
server.port=8081
